# Generated by Django 5.2.4 on 2025-08-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
