# Generated by Django 5.2.4 on 2025-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earn_spend_unit", models.PositiveIntegerField(default=100)),
                ("earn_points_per_unit", models.PositiveIntegerField(default=1)),
                ("redeem_value_per_point", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "點數規則設定",
                "verbose_name_plural": "點數規則設定",
            },
        ),
    ]
