# Generated by Django 5.2.4 on 2025-11-01 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_loyaltyconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="carrier_code",
            field=models.CharField(
                blank=True,
                help_text="格式：\\XXXXXXX 或 /XXXXXXX",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="發票載具號碼格式需為 \\XXXXXXX（前置反斜線加 7 碼英數）。",
                        regex="^/[A-Z0-9.+\\-]{7}$",
                    )
                ],
            ),
        ),
    ]
